"""campo despacho añadido a viaje

Revision ID: 0f279c1d8682
Revises: db83f5276805
Create Date: 2025-02-03 12:57:58.407651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f279c1d8682'
down_revision: Union[str, None] = 'db83f5276805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('despacho', sa.Column('_detalle_operacion_id', sa.Integer(), nullable=False))
    op.drop_constraint('despacho_detalle_operacion_id_fkey', 'despacho', type_='foreignkey')
    op.create_foreign_key(None, 'despacho', 'detalle_operacion', ['_detalle_operacion_id'], ['id'])
    op.drop_column('despacho', 'detalle_operacion_id')
    op.add_column('viaje', sa.Column('despacho', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viaje', 'despacho')
    op.add_column('despacho', sa.Column('detalle_operacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'despacho', type_='foreignkey')
    op.create_foreign_key('despacho_detalle_operacion_id_fkey', 'despacho', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.drop_column('despacho', '_detalle_operacion_id')
    # ### end Alembic commands ###
