"""cambiada logica y estructura de consumo combustible

Revision ID: 0fba1afe90a7
Revises: f5727ca89a26
Create Date: 2025-01-23 09:51:08.509325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fba1afe90a7'
down_revision: Union[str, None] = 'f5727ca89a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasto_real_camion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combustible_camion_base', sa.Float(), nullable=True),
    sa.Column('retorno_camion', sa.Float(), nullable=True),
    sa.Column('consumo_camion', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto_real_thermo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combustible_thermo_base', sa.Float(), nullable=True),
    sa.Column('retorno_thermo', sa.Float(), nullable=True),
    sa.Column('consumo_thermo', sa.Float(), nullable=True),
    sa.Column('horas_thermo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('consumo_combustible', sa.Column('gasto_real_camion_id', sa.Integer(), nullable=False))
    op.add_column('consumo_combustible', sa.Column('gasto_real_thermo_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'consumo_combustible', 'gasto_real_camion', ['gasto_real_camion_id'], ['id'])
    op.create_foreign_key(None, 'consumo_combustible', 'gasto_real_thermo', ['gasto_real_thermo_id'], ['id'])
    op.drop_column('consumo_combustible', 'combustible_thermo_base')
    op.drop_column('consumo_combustible', 'consumo_thermo')
    op.drop_column('consumo_combustible', 'retorno_camion')
    op.drop_column('consumo_combustible', 'horas_thermo')
    op.drop_column('consumo_combustible', 'combustible_camion_base')
    op.drop_column('consumo_combustible', 'retorno_thermo')
    op.drop_column('consumo_combustible', 'consumo_camion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumo_combustible', sa.Column('consumo_camion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('consumo_combustible', sa.Column('retorno_thermo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('consumo_combustible', sa.Column('combustible_camion_base', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('consumo_combustible', sa.Column('horas_thermo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('consumo_combustible', sa.Column('retorno_camion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('consumo_combustible', sa.Column('consumo_thermo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('consumo_combustible', sa.Column('combustible_thermo_base', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'consumo_combustible', type_='foreignkey')
    op.drop_constraint(None, 'consumo_combustible', type_='foreignkey')
    op.drop_column('consumo_combustible', 'gasto_real_thermo_id')
    op.drop_column('consumo_combustible', 'gasto_real_camion_id')
    op.drop_table('gasto_real_thermo')
    op.drop_table('gasto_real_camion')
    # ### end Alembic commands ###
