"""cambiada relacion de orden combustible y despacho, pasa a ser un atributo de viaje

Revision ID: 156312e3ce15
Revises: 0f279c1d8682
Create Date: 2025-02-03 14:33:42.885206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '156312e3ce15'
down_revision: Union[str, None] = '0f279c1d8682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actividad_thermo', 'temperatura_objetivo')
    op.add_column('movimiento_combustible', sa.Column('nota', sa.String(), nullable=True))
    op.drop_column('movimiento_combustible', 'tipo_movimiento')
    op.drop_column('movimiento_combustible', 'descripcion')
    op.add_column('orden_combustible', sa.Column('_detalle_operacion_id', sa.Integer(), nullable=False))
    op.drop_constraint('orden_combustible_detalle_operacion_id_fkey', 'orden_combustible', type_='foreignkey')
    op.create_foreign_key(None, 'orden_combustible', 'detalle_operacion', ['_detalle_operacion_id'], ['id'])
    op.drop_column('orden_combustible', 'fecha_orden')
    op.drop_column('orden_combustible', 'descripcion')
    op.drop_column('orden_combustible', 'costo_estimado')
    op.drop_column('orden_combustible', 'detalle_operacion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orden_combustible', sa.Column('detalle_operacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orden_combustible', sa.Column('costo_estimado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orden_combustible', sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orden_combustible', sa.Column('fecha_orden', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orden_combustible', type_='foreignkey')
    op.create_foreign_key('orden_combustible_detalle_operacion_id_fkey', 'orden_combustible', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.drop_column('orden_combustible', '_detalle_operacion_id')
    op.add_column('movimiento_combustible', sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('movimiento_combustible', sa.Column('tipo_movimiento', postgresql.ENUM('CABTHERMO', 'THERMOCAB', name='tipomovimientocombustible'), autoincrement=False, nullable=False))
    op.drop_column('movimiento_combustible', 'nota')
    op.add_column('actividad_thermo', sa.Column('temperatura_objetivo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
