"""agregada columna moneda en recibo

Revision ID: 192be8c0075b
Revises: 5cc5b8b1a4f3
Create Date: 2025-03-11 15:14:29.354236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192be8c0075b'
down_revision: Union[str, None] = '5cc5b8b1a4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recibo', sa.Column('moneda', sa.Enum('USD', 'NIO', name='moneda'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recibo', 'moneda')
    # ### end Alembic commands ###
