"""Eliminado constraint not null en fecha encendido thermo

Revision ID: 2310bce93ff9
Revises: 2ac6881319cd
Create Date: 2025-02-10 09:46:32.172208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2310bce93ff9'
down_revision: Union[str, None] = '2ac6881319cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actividad_thermo', 'fecha_hora_encendido',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actividad_thermo', 'fecha_hora_encendido',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
