"""Agregada columna de estado a detalle operacion

Revision ID: 2ac6881319cd
Revises: 678ba658910c
Create Date: 2025-02-07 10:23:59.330295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac6881319cd'
down_revision: Union[str, None] = '678ba658910c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Definir el Enum
    estado_enum = sa.Enum('CERRADO', 'ABIERTO', name='estadodetalle')

    # Crear el tipo ENUM en la base de datos si aún no existe
    estado_enum.create(op.get_bind(), checkfirst=True)

    # Agregar la columna con un valor por defecto en la base de datos
    op.add_column(
        'detalle_operacion',
        sa.Column('estado', estado_enum, nullable=False, server_default='ABIERTO')
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalle_operacion', 'estado')
    # ### end Alembic commands ###
