"""relacion de consumo con detalle operacion cambiado

Revision ID: 2b841ed256c8
Revises: fec680c0ece1
Create Date: 2025-01-23 10:59:49.906279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b841ed256c8'
down_revision: Union[str, None] = 'fec680c0ece1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_operacion', sa.Column('consumo_combustible_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'detalle_operacion', 'consumo_combustible', ['consumo_combustible_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalle_operacion', type_='foreignkey')
    op.drop_column('detalle_operacion', 'consumo_combustible_id')
    # ### end Alembic commands ###
