"""Estrucutra de datos historicos para el consumo de combustible de los camiones en base a los destinos, clientes, lugar de carga y movimiento adicional

Revision ID: 35bf4b5ee63a
Revises: e1dc8873b2d0
Create Date: 2025-02-20 11:02:33.694834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35bf4b5ee63a'
down_revision: Union[str, None] = 'e1dc8873b2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referencia_consumo_combustible',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_referencia', sa.Enum('BASE', 'TRIANGULADO', 'POR_PESO', name='tiporeferencia'), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('lugar_carga_id', sa.Integer(), nullable=True),
    sa.Column('ruta_movimiento_id', sa.Integer(), nullable=True),
    sa.Column('peso_min', sa.Float(), nullable=True),
    sa.Column('peso_max', sa.Float(), nullable=True),
    sa.Column('consumo_galones', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['destino_id'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['lugar_carga_id'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['ruta_movimiento_id'], ['ruta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camion_criterio_consumo',
    sa.Column('camion_id', sa.Integer(), nullable=False),
    sa.Column('criterio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camion_id'], ['camion.id'], ),
    sa.ForeignKeyConstraint(['criterio_id'], ['referencia_consumo_combustible.id'], ),
    sa.PrimaryKeyConstraint('camion_id', 'criterio_id')
    )
    op.alter_column('descarga', 'fecha_poscionamiento', new_column_name='fecha_posicionamiento')
    op.add_column('descarga', sa.Column('_lugar_carga_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'descarga', 'ubicacion', ['_lugar_carga_id'], ['id'])
    op.add_column('gasto_real_camion', sa.Column('circuito_id', sa.Integer(), nullable=False))
    op.drop_constraint('gasto_real_camion_detalle_operacion_id_fkey', 'gasto_real_camion', type_='foreignkey')
    op.create_foreign_key(None, 'gasto_real_camion', 'circuito', ['circuito_id'], ['id'])
    op.drop_column('gasto_real_camion', 'detalle_operacion_id')
    op.drop_column('movimiento_adicional', 'gasto_combustible')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimiento_adicional', sa.Column('gasto_combustible', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('gasto_real_camion', sa.Column('detalle_operacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gasto_real_camion', type_='foreignkey')
    op.create_foreign_key('gasto_real_camion_detalle_operacion_id_fkey', 'gasto_real_camion', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.drop_column('gasto_real_camion', 'circuito_id')
    op.add_column('descarga', sa.Column('fecha_poscionamiento', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'descarga', type_='foreignkey')
    op.drop_column('descarga', '_lugar_carga_id')
    op.drop_column('descarga', 'fecha_posicionamiento')
    op.drop_table('camion_criterio_consumo')
    op.drop_table('referencia_consumo_combustible')
    # ### end Alembic commands ###
