"""Cambios orden de combustible

Revision ID: 3a65e4fd7445
Revises: 4e7b003ea188
Create Date: 2025-10-14 12:04:10.125504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a65e4fd7445'
down_revision: Union[str, None] = '4e7b003ea188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    tipo_enum = sa.Enum('CAMION', 'THERMO', name='tipoordencombustible')

    tipo_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('orden_combustible', sa.Column('tipo',tipo_enum, nullable=False, server_default='CAMION'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orden_combustible', 'tipo')
    # ### end Alembic commands ###
