"""Modificaciones a thermmo para soportar el calculo del consumo de combustible

Revision ID: 42f6ec189b3e
Revises: ee94221b8568
Create Date: 2025-01-21 12:08:14.079111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f6ec189b3e'
down_revision: Union[str, None] = 'ee94221b8568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos_historicos_consumo_thermo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thermo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('rendimiento', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['thermo_id'], ['thermo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelo_consumo_thermo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thermo_id', sa.Integer(), nullable=False),
    sa.Column('pendiente', sa.Float(), nullable=True),
    sa.Column('interseccion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['thermo_id'], ['thermo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('descarga', sa.Column('peso', sa.String(), nullable=True))
    op.execute(
    """
    ALTER TABLE viaje 
    ALTER COLUMN temperatura TYPE double precision 
    USING temperatura::double precision
    """
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viaje', 'temperatura',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('descarga', 'peso')
    op.drop_table('modelo_consumo_thermo')
    op.drop_table('datos_historicos_consumo_thermo')
    # ### end Alembic commands ###
