"""total y subtotal de factura puestos como privados

Revision ID: 4398d91d790f
Revises: 8aaccc7ea923
Create Date: 2025-03-07 09:21:10.867834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4398d91d790f'
down_revision: Union[str, None] = '8aaccc7ea923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factura', sa.Column('_subtotal', sa.Float(), nullable=False))
    op.add_column('factura', sa.Column('_total', sa.Float(), nullable=False))
    op.drop_column('factura', 'subtotal')
    op.drop_column('factura', 'total')
    op.add_column('gasto', sa.Column('moneda', sa.Enum('USD', 'NIO', name='moneda'), nullable=False))
    op.alter_column('movimiento_adicional', 'ruta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movimiento_adicional', 'ruta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('gasto', 'moneda')
    op.add_column('factura', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('factura', sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('factura', '_total')
    op.drop_column('factura', '_subtotal')
    # ### end Alembic commands ###
