"""Agregada columna estado para Thermo, furgon sobre la base de estadocamion

Revision ID: 4e7b003ea188
Revises: 76dbd71b91f8
Create Date: 2025-09-04 23:29:08.634281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e7b003ea188'
down_revision: Union[str, None] = '76dbd71b91f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

estado_enum = postgresql.ENUM(
    'ACTIVO', 'MANTENIMIENTO', 'BAJA', 'ENVIAJE',
    name='estadocamion',
    create_type=False,          # 👈 reutiliza el tipo existente, no lo crea
    # schema='public',          # 👈 ajusta si tu tipo vive fuera de 'public'
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despacho',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_detalle_operacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=False),
    sa.Column('monto_entregado', sa.Float(), nullable=False),
    sa.Column('monto_sobrante_anterior_circuito', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['_detalle_operacion_id'], ['detalle_operacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'furgon',
        sa.Column(
            'estado',
            estado_enum,
            nullable=False,
            # ser explícitos con el cast evita sorpresas
            server_default=sa.text("'ACTIVO'::estadocamion"),
        ),
    )
    op.add_column(
        'thermo',
        sa.Column(
            'estado',
            estado_enum,
            nullable=False,
            server_default=sa.text("'ACTIVO'::estadocamion"),
        ),
    )
    ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thermo', 'estado')
    op.drop_column('furgon', 'estado')
    op.create_table('permissions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('permissions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    sa.UniqueConstraint('resource', 'action', name='permissions_resource_action_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('roles',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='roles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('role_permissions',
    sa.Column('role_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='role_permissions_permission_id_fkey'),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], name='role_permissions_role_name_fkey'),
    sa.PrimaryKeyConstraint('role_name', 'permission_id', name='role_permissions_pkey')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grant_or_deny', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='user_permissions_permission_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_permissions_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', name='user_permissions_pkey')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], name='user_roles_role_name_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_roles_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'role_name', name='user_roles_pkey')
    )
    op.drop_table('despacho')
    # ### end Alembic commands ###
