"""Columna despacho renombrada a viatico en viaje

Revision ID: 54b2201e25e9
Revises: 156312e3ce15
Create Date: 2025-02-04 09:55:15.581337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b2201e25e9'
down_revision: Union[str, None] = '156312e3ce15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaje', sa.Column('viaticos', sa.Float(), nullable=False))
    op.drop_column('viaje', 'despacho')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaje', sa.Column('despacho', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('viaje', 'viaticos')
    # ### end Alembic commands ###
