"""clase viaje cambiada, ahora soporta una herencia polimorfica utilizando STI para persistit los datos

Revision ID: 5774f502e33f
Revises: 728f3ebd6c6d
Create Date: 2025-02-25 09:59:23.056273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5774f502e33f'
down_revision: Union[str, None] = '728f3ebd6c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimiento_combustible', 'fecha_movimiento')
    op.add_column('viaje', sa.Column('viaticos_importacion', sa.Float(), nullable=False))
    op.add_column('viaje', sa.Column('retorno_viaticos', sa.Float(), nullable=False))
    op.alter_column('viaje', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viaje', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('viaje', 'retorno_viaticos')
    op.drop_column('viaje', 'viaticos_importacion')
    op.add_column('movimiento_combustible', sa.Column('fecha_movimiento', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
