"""Cascade agregado a tablas relacionadas a detalle operacion, viaje y circuito

Revision ID: 5cc5b8b1a4f3
Revises: f918351b6a9a
Create Date: 2025-03-10 12:07:25.014617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc5b8b1a4f3'
down_revision: Union[str, None] = 'f918351b6a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actividad_thermo_detalle_operacion_id_fkey', 'actividad_thermo', type_='foreignkey')
    op.create_foreign_key(None, 'actividad_thermo', 'detalle_operacion', ['detalle_operacion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('descarga_detalle_operacion_id_fkey', 'descarga', type_='foreignkey')
    op.create_foreign_key(None, 'descarga', 'detalle_operacion', ['detalle_operacion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('detalle_factura_factura_id_fkey', 'detalle_factura', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_factura', 'factura', ['factura_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('detalle_operacion_viaje_id_fkey', 'detalle_operacion', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_operacion', 'viaje', ['viaje_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('gasto_real_camion_circuito_id_fkey', 'gasto_real_camion', type_='foreignkey')
    op.create_foreign_key(None, 'gasto_real_camion', 'circuito', ['circuito_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('gasto_real_thermo_detalle_operacion_id_fkey', 'gasto_real_thermo', type_='foreignkey')
    op.create_foreign_key(None, 'gasto_real_thermo', 'detalle_operacion', ['detalle_operacion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('movimiento_adicional_circuito_id_fkey', 'movimiento_adicional', type_='foreignkey')
    op.create_foreign_key(None, 'movimiento_adicional', 'circuito', ['circuito_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('movimiento_combustible_detalle_operacion_id_fkey', 'movimiento_combustible', type_='foreignkey')
    op.create_foreign_key(None, 'movimiento_combustible', 'detalle_operacion', ['detalle_operacion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('orden_combustible__detalle_operacion_id_fkey', 'orden_combustible', type_='foreignkey')
    op.create_foreign_key(None, 'orden_combustible', 'detalle_operacion', ['detalle_operacion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('viaje__circuito_id_fkey', 'viaje', type_='foreignkey')
    op.create_foreign_key(None, 'viaje', 'circuito', ['_circuito_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viaje', type_='foreignkey')
    op.create_foreign_key('viaje__circuito_id_fkey', 'viaje', 'circuito', ['_circuito_id'], ['id'])
    op.drop_constraint(None, 'orden_combustible', type_='foreignkey')
    op.create_foreign_key('orden_combustible__detalle_operacion_id_fkey', 'orden_combustible', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.drop_constraint(None, 'movimiento_combustible', type_='foreignkey')
    op.create_foreign_key('movimiento_combustible_detalle_operacion_id_fkey', 'movimiento_combustible', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.drop_constraint(None, 'movimiento_adicional', type_='foreignkey')
    op.create_foreign_key('movimiento_adicional_circuito_id_fkey', 'movimiento_adicional', 'circuito', ['circuito_id'], ['id'])
    op.drop_constraint(None, 'gasto_real_thermo', type_='foreignkey')
    op.create_foreign_key('gasto_real_thermo_detalle_operacion_id_fkey', 'gasto_real_thermo', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.drop_constraint(None, 'gasto_real_camion', type_='foreignkey')
    op.create_foreign_key('gasto_real_camion_circuito_id_fkey', 'gasto_real_camion', 'circuito', ['circuito_id'], ['id'])
    op.drop_constraint(None, 'detalle_operacion', type_='foreignkey')
    op.create_foreign_key('detalle_operacion_viaje_id_fkey', 'detalle_operacion', 'viaje', ['viaje_id'], ['id'])
    op.drop_constraint(None, 'detalle_factura', type_='foreignkey')
    op.create_foreign_key('detalle_factura_factura_id_fkey', 'detalle_factura', 'factura', ['factura_id'], ['id'])
    op.drop_constraint(None, 'descarga', type_='foreignkey')
    op.create_foreign_key('descarga_detalle_operacion_id_fkey', 'descarga', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.drop_constraint(None, 'actividad_thermo', type_='foreignkey')
    op.create_foreign_key('actividad_thermo_detalle_operacion_id_fkey', 'actividad_thermo', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    # ### end Alembic commands ###
