"""Consumo combustibe eliminado para simplificar las relaciones de gasto real

Revision ID: 678ba658910c
Revises: f7530652ac53
Create Date: 2025-02-06 10:36:16.130414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678ba658910c'
down_revision: Union[str, None] = 'f7530652ac53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gasto_real_camion_consumo_combustible_id_fkey', 'gasto_real_camion', type_='foreignkey')
    op.drop_constraint('gasto_real_thermo_consumo_combustible_id_fkey', 'gasto_real_thermo', type_='foreignkey')
    
    op.add_column('gasto_real_thermo', sa.Column('detalle_operacion_id', sa.Integer(), nullable=False))
    op.add_column('gasto_real_camion', sa.Column('detalle_operacion_id', sa.Integer(), nullable=False))

    op.create_foreign_key(None, 'gasto_real_thermo', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.create_foreign_key(None, 'gasto_real_camion', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    
    op.drop_column('gasto_real_camion', 'consumo_combustible_id')
    op.drop_column('gasto_real_thermo', 'consumo_combustible_id')

    op.drop_table('consumo_combustible')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasto_real_thermo', sa.Column('consumo_combustible_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gasto_real_thermo', type_='foreignkey')
    op.create_foreign_key('gasto_real_thermo_consumo_combustible_id_fkey', 'gasto_real_thermo', 'consumo_combustible', ['consumo_combustible_id'], ['id'])
    op.drop_column('gasto_real_thermo', 'detalle_operacion_id')
    op.add_column('gasto_real_camion', sa.Column('consumo_combustible_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gasto_real_camion', type_='foreignkey')
    op.create_foreign_key('gasto_real_camion_consumo_combustible_id_fkey', 'gasto_real_camion', 'consumo_combustible', ['consumo_combustible_id'], ['id'])
    op.drop_column('gasto_real_camion', 'detalle_operacion_id')
    op.create_table('consumo_combustible',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('detalle_operacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['detalle_operacion_id'], ['detalle_operacion.id'], name='consumo_combustible_detalle_operacion_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='consumo_combustible_pkey')
    )
    # ### end Alembic commands ###
