"""Cambiada columna fecha movimiento para ser nullable en movimiento adicional

Revision ID: 6d7a5c6cee3e
Revises: 54b2201e25e9
Create Date: 2025-02-04 10:16:41.898583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d7a5c6cee3e'
down_revision: Union[str, None] = '54b2201e25e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movimiento_adicional', 'fecha_movimiento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movimiento_adicional', 'fecha_movimiento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
