"""Cambiado atributo detalle operacion de ordenes combustible para que no sea privado

Revision ID: 728f3ebd6c6d
Revises: f66c3ba5b3c1
Create Date: 2025-02-21 11:59:17.851625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728f3ebd6c6d'
down_revision: Union[str, None] = 'f66c3ba5b3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orden_combustible', '_detalle_operacion_id', new_column_name='detalle_operacion_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orden_combustible', sa.Column('_detalle_operacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orden_combustible', type_='foreignkey')
    op.create_foreign_key('orden_combustible__detalle_operacion_id_fkey', 'orden_combustible', 'detalle_operacion', ['_detalle_operacion_id'], ['id'])
    op.drop_column('orden_combustible', 'detalle_operacion_id')
    # ### end Alembic commands ###
