"""Agregada columna descripcion a tarifas flete

Revision ID: 768ec63b26f8
Revises: 8e9ea98ee499
Create Date: 2025-01-17 10:35:57.168317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768ec63b26f8'
down_revision: Union[str, None] = '8e9ea98ee499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarifa_flete', sa.Column('descripcion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarifa_flete', 'descripcion')
    # ### end Alembic commands ###
