"""Actualizacion de enums de estados de multiples clases

Revision ID: 76dbd71b91f8
Revises: f354301d9c33
Create Date: 2025-03-25 11:17:47.125724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76dbd71b91f8'
down_revision: Union[str, None] = 'f354301d9c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
