"""Eliminacion de costo y moneda en viaje

Revision ID: ab1e24423fff
Revises: d27b052aa890
Create Date: 2025-02-21 09:47:42.843611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab1e24423fff'
down_revision: Union[str, None] = 'd27b052aa890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viaje', '_moneda')
    op.drop_column('viaje', '_costo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaje', sa.Column('_costo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('viaje', sa.Column('_moneda', postgresql.ENUM('USD', 'NIO', name='moneda'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
