"""Estructura de movimiento adcional modificada para relacionarse con detalle operacion

Revision ID: b9acdbd696b9
Revises: e91bda94c1e4
Create Date: 2025-01-31 10:35:38.966209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9acdbd696b9'
down_revision: Union[str, None] = 'e91bda94c1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividad_thermo', sa.Column('_duracion_horas', sa.Float(), nullable=True))
    op.drop_column('actividad_thermo', 'duracion_horas')
    op.add_column('descarga', sa.Column('_dias_viajados', sa.Integer(), nullable=True))
    op.drop_column('descarga', 'dias_viajados')
    op.add_column('gasto_real_camion', sa.Column('combustible_base_camion', sa.Float(), nullable=True))
    op.add_column('gasto_real_camion', sa.Column('_consumo_camion', sa.Float(), nullable=True))
    op.drop_column('gasto_real_camion', 'consumo_camion')
    op.drop_column('gasto_real_camion', 'combustible_camion_base')
    op.add_column('gasto_real_thermo', sa.Column('combustible_base_thermo', sa.Float(), nullable=True))
    op.add_column('gasto_real_thermo', sa.Column('_consumo_thermo', sa.Float(), nullable=True))
    op.drop_column('gasto_real_thermo', 'consumo_thermo')
    op.drop_column('gasto_real_thermo', 'combustible_thermo_base')
    op.add_column('movimiento_adicional', sa.Column('detalle_operacion_id', sa.Integer(), nullable=False))
    op.drop_constraint('movimiento_adicional_circuito_id_fkey', 'movimiento_adicional', type_='foreignkey')
    op.create_foreign_key(None, 'movimiento_adicional', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.drop_column('movimiento_adicional', 'circuito_id')

    gasolinera_enum = sa.Enum('NEDICSA', 'MOVIL', 'SV', name='gasolinera')

    gasolinera_enum.create(op.get_bind(), checkfirst=True)

    op.execute("ALTER TABLE orden_combustible ALTER COLUMN gasolinera TYPE gasolinera USING gasolinera::gasolinera")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orden_combustible', 'gasolinera',
               existing_type=sa.Enum('NEDICSA', 'MOVIL', 'SV', name='gasolinera'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('movimiento_adicional', sa.Column('circuito_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'movimiento_adicional', type_='foreignkey')
    op.create_foreign_key('movimiento_adicional_circuito_id_fkey', 'movimiento_adicional', 'circuito', ['circuito_id'], ['id'])
    op.drop_column('movimiento_adicional', 'detalle_operacion_id')
    op.add_column('gasto_real_thermo', sa.Column('combustible_thermo_base', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('gasto_real_thermo', sa.Column('consumo_thermo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('gasto_real_thermo', '_consumo_thermo')
    op.drop_column('gasto_real_thermo', 'combustible_base_thermo')
    op.add_column('gasto_real_camion', sa.Column('combustible_camion_base', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('gasto_real_camion', sa.Column('consumo_camion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('gasto_real_camion', '_consumo_camion')
    op.drop_column('gasto_real_camion', 'combustible_base_camion')
    op.add_column('descarga', sa.Column('dias_viajados', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('descarga', '_dias_viajados')
    op.add_column('actividad_thermo', sa.Column('duracion_horas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('actividad_thermo', '_duracion_horas')
    # ### end Alembic commands ###
