"""Movimiento adicional cambiado para relacionarse con Circuito

Revision ID: d27b052aa890
Revises: 35bf4b5ee63a
Create Date: 2025-02-21 09:30:37.733787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27b052aa890'
down_revision: Union[str, None] = '35bf4b5ee63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimiento_adicional', sa.Column('circuito_id', sa.Integer(), nullable=False))
    op.drop_constraint('movimiento_adicional_detalle_operacion_id_fkey', 'movimiento_adicional', type_='foreignkey')
    op.create_foreign_key(None, 'movimiento_adicional', 'circuito', ['circuito_id'], ['id'])
    op.drop_column('movimiento_adicional', 'detalle_operacion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimiento_adicional', sa.Column('detalle_operacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'movimiento_adicional', type_='foreignkey')
    op.create_foreign_key('movimiento_adicional_detalle_operacion_id_fkey', 'movimiento_adicional', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.drop_column('movimiento_adicional', 'circuito_id')
    # ### end Alembic commands ###
