"""Cambiada esturctura de despacho, detalle operacion, circuito y viaje

Revision ID: d413a30f36cc
Revises: b9acdbd696b9
Create Date: 2025-01-31 12:09:17.935422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd413a30f36cc'
down_revision: Union[str, None] = 'b9acdbd696b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('circuito_conductor_id_fkey', 'circuito', type_='foreignkey')
    op.drop_constraint('circuito_viaje_vuelta_id_fkey', 'circuito', type_='foreignkey')
    op.drop_constraint('circuito_viaje_ida_id_fkey', 'circuito', type_='foreignkey')
    op.drop_column('circuito', 'conductor_id')
    op.drop_column('circuito', 'viaje_vuelta_id')
    op.drop_column('circuito', 'viaje_ida_id')
    op.add_column('despacho', sa.Column('detalle_operacion_id', sa.Integer(), nullable=False))
    op.drop_constraint('despacho_circuito_id_fkey', 'despacho', type_='foreignkey')
    op.create_foreign_key(None, 'despacho', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.drop_column('despacho', 'circuito_id')
    op.add_column('viaje', sa.Column('_circuito_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'viaje', 'circuito', ['_circuito_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viaje', type_='foreignkey')
    op.drop_column('viaje', '_circuito_id')
    op.add_column('despacho', sa.Column('circuito_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'despacho', type_='foreignkey')
    op.create_foreign_key('despacho_circuito_id_fkey', 'despacho', 'circuito', ['circuito_id'], ['id'])
    op.drop_column('despacho', 'detalle_operacion_id')
    op.add_column('circuito', sa.Column('viaje_ida_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('circuito', sa.Column('viaje_vuelta_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('circuito', sa.Column('conductor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('circuito_viaje_ida_id_fkey', 'circuito', 'viaje', ['viaje_ida_id'], ['id'])
    op.create_foreign_key('circuito_viaje_vuelta_id_fkey', 'circuito', 'viaje', ['viaje_vuelta_id'], ['id'])
    op.create_foreign_key('circuito_conductor_id_fkey', 'circuito', 'conductor', ['conductor_id'], ['id'])
    # ### end Alembic commands ###
