"""ocultadas columnas en viaje

Revision ID: db83f5276805
Revises: d413a30f36cc
Create Date: 2025-02-03 11:12:09.088606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db83f5276805'
down_revision: Union[str, None] = 'd413a30f36cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaje', sa.Column('_costo', sa.Float(), nullable=False))
    op.add_column('viaje', sa.Column('_moneda', sa.Enum('USD', 'NIO', name='moneda'), nullable=False))
    op.add_column('viaje', sa.Column('_facturado', sa.Boolean(), nullable=False))
    op.drop_column('viaje', 'moneda')
    op.drop_column('viaje', 'costo')
    op.drop_column('viaje', 'facturado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaje', sa.Column('facturado', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('viaje', sa.Column('costo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('viaje', sa.Column('moneda', postgresql.ENUM('USD', 'NIO', name='moneda'), autoincrement=False, nullable=False))
    op.drop_column('viaje', '_facturado')
    op.drop_column('viaje', '_moneda')
    op.drop_column('viaje', '_costo')
    # ### end Alembic commands ###
