"""Cambiada columna de combustible base thermo

Revision ID: e1dc8873b2d0
Revises: 2310bce93ff9
Create Date: 2025-02-10 10:47:02.630620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1dc8873b2d0'
down_revision: Union[str, None] = '2310bce93ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasto_real_thermo', sa.Column('_combustible_base_thermo', sa.Float(), nullable=True))
    op.drop_column('gasto_real_thermo', 'combustible_base_thermo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasto_real_thermo', sa.Column('combustible_base_thermo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('gasto_real_thermo', '_combustible_base_thermo')
    # ### end Alembic commands ###
