"""relaciones de consumo con gasto real modificadas

Revision ID: e91bda94c1e4
Revises: 2b841ed256c8
Create Date: 2025-01-23 11:30:54.105503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91bda94c1e4'
down_revision: Union[str, None] = '2b841ed256c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumo_combustible', sa.Column('detalle_operacion_id', sa.Integer(), nullable=False))
    op.drop_constraint('consumo_combustible_gasto_real_camion_id_fkey', 'consumo_combustible', type_='foreignkey')
    op.drop_constraint('consumo_combustible_gasto_real_thermo_id_fkey', 'consumo_combustible', type_='foreignkey')
    op.create_foreign_key(None, 'consumo_combustible', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    op.drop_column('consumo_combustible', 'gasto_real_camion_id')
    op.drop_column('consumo_combustible', 'gasto_real_thermo_id')
    op.drop_constraint('detalle_operacion_consumo_combustible_id_fkey', 'detalle_operacion', type_='foreignkey')
    op.drop_column('detalle_operacion', 'consumo_combustible_id')
    op.add_column('gasto_real_camion', sa.Column('consumo_combustible_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'gasto_real_camion', 'consumo_combustible', ['consumo_combustible_id'], ['id'])
    op.add_column('gasto_real_thermo', sa.Column('consumo_combustible_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'gasto_real_thermo', 'consumo_combustible', ['consumo_combustible_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gasto_real_thermo', type_='foreignkey')
    op.drop_column('gasto_real_thermo', 'consumo_combustible_id')
    op.drop_constraint(None, 'gasto_real_camion', type_='foreignkey')
    op.drop_column('gasto_real_camion', 'consumo_combustible_id')
    op.add_column('detalle_operacion', sa.Column('consumo_combustible_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('detalle_operacion_consumo_combustible_id_fkey', 'detalle_operacion', 'consumo_combustible', ['consumo_combustible_id'], ['id'])
    op.add_column('consumo_combustible', sa.Column('gasto_real_thermo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('consumo_combustible', sa.Column('gasto_real_camion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'consumo_combustible', type_='foreignkey')
    op.create_foreign_key('consumo_combustible_gasto_real_thermo_id_fkey', 'consumo_combustible', 'gasto_real_thermo', ['gasto_real_thermo_id'], ['id'])
    op.create_foreign_key('consumo_combustible_gasto_real_camion_id_fkey', 'consumo_combustible', 'gasto_real_camion', ['gasto_real_camion_id'], ['id'])
    op.drop_column('consumo_combustible', 'detalle_operacion_id')
    # ### end Alembic commands ###
