"""Cambio de fecha_posicionamiento a nullable (viaje y descarga)

Revision ID: ec738150e5b7
Revises: 7b21a6dfe92e
Create Date: 2025-11-14 09:29:12.249340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec738150e5b7'
down_revision: Union[str, None] = '7b21a6dfe92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('descarga', 'fecha_posicionamiento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('viaje', 'fecha_posicionamiento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_viaje_estado_facturacion', 'viaje', ['estado_facturacion'], unique=False)
    op.alter_column('viaje', 'fecha_posicionamiento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('descarga', 'fecha_posicionamiento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    
