"""Eliminadas columnas de rendimiento en Thermo

Revision ID: ee94221b8568
Revises: 768ec63b26f8
Create Date: 2025-01-20 11:01:12.295005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee94221b8568'
down_revision: Union[str, None] = '768ec63b26f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thermo', 'rendimiento_fresco')
    op.drop_column('thermo', 'rendimiento_congelado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thermo', sa.Column('rendimiento_congelado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('thermo', sa.Column('rendimiento_fresco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
