"""Cambiado estado en camiones y conductores

Revision ID: f354301d9c33
Revises: 192be8c0075b
Create Date: 2025-03-14 10:15:06.973249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f354301d9c33'
down_revision: Union[str, None] = '192be8c0075b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # --- Para la tabla "camion" ---
    # Crear el nuevo tipo ENUM para la columna 'estado' en la tabla 'camion'
    camion_estado_enum = postgresql.ENUM('ACTIVO', 'MANTENIMIENTO', 'BAJA', name='estadocamion')
    camion_estado_enum.create(op.get_bind(), checkfirst=True)
    
    # Borrar la columna 'estado' (se perderán los datos)
    op.drop_column('camion', 'estado')
    # Agregar la columna 'estado' con server_default (por ejemplo, 'ACTIVO')
    op.add_column(
        'camion',
        sa.Column('estado', camion_estado_enum, nullable=False, server_default='ACTIVO')
    )
    
    # Eliminar la columna 'disponibilidad' de la tabla 'camion'
    op.drop_column('camion', 'disponibilidad')
    
    # --- Para la tabla "conductor" ---
    # Crear el tipo ENUM para el estado del conductor
    conductor_estado_enum = postgresql.ENUM('VIAJE', 'DISPONIBLE', 'BAJA', name='estadoconductor')
    conductor_estado_enum.create(op.get_bind(), checkfirst=True)
    
    # Agregar la columna 'estado' con server_default 'DISPONIBLE'
    op.add_column(
        'conductor',
        sa.Column('estado', conductor_estado_enum, nullable=False, server_default='DISPONIBLE')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conductor', 'estado')
    op.add_column('camion', sa.Column('disponibilidad', postgresql.ENUM('DISPONIBLE', 'MANTENIMIENTO', 'ENVIAJE', name='disponibilidad'), autoincrement=False, nullable=False))
    op.alter_column('camion', 'estado',
               existing_type=sa.Enum('ACTIVO', 'MANTENIMIENTO', 'BAJA', name='estadocamion'),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
