"""agregadas relaciones con modelo_consumo en thermo

Revision ID: f5727ca89a26
Revises: 42f6ec189b3e
Create Date: 2025-01-22 08:34:19.717260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5727ca89a26'
down_revision: Union[str, None] = '42f6ec189b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
