"""Cambio de nombre de combustible base thermo para que deje de tratarse como privado

Revision ID: f66c3ba5b3c1
Revises: ab1e24423fff
Create Date: 2025-02-21 11:45:04.439822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66c3ba5b3c1'
down_revision: Union[str, None] = 'ab1e24423fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasto_real_thermo', sa.Column('combustible_base_thermo', sa.Float(), nullable=True))
    op.drop_column('gasto_real_thermo', '_combustible_base_thermo')
    op.alter_column('viaje', 'temperatura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viaje', 'temperatura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('gasto_real_thermo', sa.Column('_combustible_base_thermo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('gasto_real_thermo', 'combustible_base_thermo')
    # ### end Alembic commands ###
