"""Cambios al gasto thermo

Revision ID: f7530652ac53
Revises: 6d7a5c6cee3e
Create Date: 2025-02-06 10:00:23.929136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7530652ac53'
down_revision: Union[str, None] = '6d7a5c6cee3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasto_real_thermo', sa.Column('restante_thermo', sa.Float(), nullable=True))
    op.drop_column('gasto_real_thermo', 'horas_thermo')
    op.drop_column('gasto_real_thermo', 'retorno_thermo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasto_real_thermo', sa.Column('retorno_thermo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('gasto_real_thermo', sa.Column('horas_thermo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('gasto_real_thermo', 'restante_thermo')
    # ### end Alembic commands ###
