"""Añadida columna costo en detalle factura

Revision ID: f918351b6a9a
Revises: 4398d91d790f
Create Date: 2025-03-10 11:58:44.677621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f918351b6a9a'
down_revision: Union[str, None] = '4398d91d790f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_factura', sa.Column('costo', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalle_factura', 'costo')
    # ### end Alembic commands ###
