"""relacion de consumo con detalle operacion cambiado

Revision ID: fec680c0ece1
Revises: 0fba1afe90a7
Create Date: 2025-01-23 10:58:08.766452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec680c0ece1'
down_revision: Union[str, None] = '0fba1afe90a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('consumo_combustible_detalle_operacion_id_fkey', 'consumo_combustible', type_='foreignkey')
    op.drop_column('consumo_combustible', 'detalle_operacion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumo_combustible', sa.Column('detalle_operacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('consumo_combustible_detalle_operacion_id_fkey', 'consumo_combustible', 'detalle_operacion', ['detalle_operacion_id'], ['id'])
    # ### end Alembic commands ###
