"""Authorization persistence contract for roles, grants, and overrides."""

from collections.abc import Iterable, Sequence
from typing import Protocol

from ..entities.permission_cell import PermissionCell
from ..entities.role import Role


class AuthorizationStore(Protocol):
    def list_roles(self) -> list[Role]: ...
    def create_role(self, role_name: str) -> Role: ...
    def delete_role(self, role_name: str) -> None: ...
    def get_role_permissions(self, role_name: str) -> list[PermissionCell]: ...
    def set_role_permissions(self, role_name: str, permissions: Sequence[PermissionCell]) -> None: ...
    def assign_roles_to_user(self, username: str, role_names: Iterable[str], replace: bool = True) -> None: ...
    def set_user_permissions(self, username: str, permissions: list[PermissionCell]) -> None: ...
    def set_user_permission_states(self, username: str, permission_states: Sequence[PermissionCell]) -> None: ...
    def read_profile(self, username: str) -> dict: ...
